#!/bin/bash
#Gitlab setup
#1.update your os
sudo apt-get update
sudo apt-get install -y postfix
#2. Add the GitLab package repository and install the package
curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash
#3.configure (Need to modify gilab url under /ect/gitlab/gitlab.rb and post run the bleow cmd)
sudo gitlab-ctl reconfigure
sudo gitlab-ctl restart
